---
- name: setup john the ripper
  hosts: localhost
  tasks:
  - name: install build dependencies
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - make
      - gcc
      - openssl-devel
  - name: create /scratch directory
    file:
      path: /scratch
      state: directory
  - name: git clone
    git:
      repo: 'https://github.com/openwall/john.git'
      dest: /scratch/john
      clone: true
  - name: compile john
    shell: "{{ item }}"
    args:
      chdir: /scratch/john/src
    loop:
      - './configure && make -sj4'
      - 'make -s clean && make -sj4'
  - name: create alias for john
    lineinfile:
      path: '/root/.bashrc'
      line: 'alias john=/scratch/john/run/john'
  - name: create overlay for john
    shell: "{{ item }}"
    loop:
      - 'wwctl overlay create john'
      - 'wwctl overlay mkdir john /scratch/john'
      - 'split -n 3 -d /scratch/john/run/password.lst /scratch/john/run/passwordlist_'
      - 'cp -r /scratch/john/run /var/lib/warewulf/overlays/john/scratch/john/'
      - 'wwctl overlay build -NH'

- name: john hashes for tests
  hosts: localhost
  tasks:
  - name: set creds
    set_fact:
      password_data:
        - name: "user1"
          password: "m0n3y4m3"
        - name: "admin"
          password: "FOXxIE98"
        - name: "root"
          password: "Lego#las21"
        - name: "mysql"
          password: "RAInwatEr7"
        - name: "elastic"
          password: "sstayoff4k"
        - name: "Administrator"
          password: "Safeway21123"
        - name: "service"
          password: "|aekwondo17"
        - name: "superuser"
          password: "FArMbOy33"
        - name: "helpdesk"
          password: "Hawa1187"
        - name: "streetrack"
          password: "s@mbarock"
  - name: create hash for each password
    shell: "echo -n '{{ item.password }}' | sha256sum | cut -d ' ' -f 1"
    loop: "{{ password_data }}"
    register: hash_results
  - name: create slurm directory on NFS share
    file:
      path: /home/slurm
      state: directory
  - name: create passwd file with hashed passwords
    copy:
      content: |
        {% for item in hash_results.results %}
        {{ item.item.name }}:{{ item.stdout }}
        {% endfor %}
      dest: /home/slurm/john_hash.txt
  - name: copy test scripts to nfs share
    copy:
      src: "{{ item }}"
      dest: /home/slurm/
      mode: '0755'
    loop:
      - './john_test.sh'
      - './john_distributed.sh'
