---
- name: run timesync playbook
  import_playbook: ./timesync.yaml

- name: setup slurm
  hosts: localhost
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - munge
      - slurm  
      - ignition
      - gdisk
  - name: create slurm user
    user:
      name: slurm
      uid: 1000
      groups: munge
  - name: install slurmd
    yum:
      name: slurm-slurmd
      state: present
  - name: enable munge
    shell: 'systemctl enable munge'
  - name: slurm
    template:
      src: slurm.j2
      dest: /etc/slurm/slurm.conf
  - name: slurmd permissions
    shell: "{{ item }}"
    loop:
      - 'mkdir -p /var/log/slurm /var/run/slurm /var/spool/slurmd.spool'
      - 'chown -R slurm:slurm /var/log/slurm /var/run/slurm /var/spool/slurmd.spool'
      - 'chmod -R 755 /var/log/slurm /var/run/slurm /var/spool/slurmd.spool'
  - name: enable slurmd
    shell: 'systemctl enable slurmd'
