---
- name: setup slurm
  hosts: all
  tasks:
  - name: create slurm_packages directory
    file:
      path: /home
      state: directory
    when: ansible_hostname == 'control'
  - name: download slurm_packages
    yum:
      name: slurm-slurmd
      download_only: true
      download_dir: /home/slurm_packages
    when: ansible_hostname == 'control'
  - name: clear repos on nodes and install slurm
    shell: "{{ item }}"
    loop:
      - rm -rf /etc/yum.repos.d/*
      - dnf install /home/slurm_packages/*.rpm
    when: inventory_hostname in groups['nodes']

