---
- name: run timesync playbook
  import_playbook: ./timesync.yaml

- name: setup slurm
  hosts: localhost
  tasks:
  - name: create slurm user
    user:
      name: slurm
      system: true
  - name: install slurm packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - munge
      - munge-libs
      - slurm
      - slurm-perlapi
  - name: install slurmctld
    yum:
      name: slurm-slurmctld
      state: present
  - name: generate munge key and syncuser 
    shell: "{{ item }}"
    loop:
      - 'dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key'
      - 'wwctl container syncuser --write rockylinux-9 --build'
  - name: chown munge.key
    file:
      path: /etc/munge/munge.key
      mode: '0400'
      owner: munge
      group: slurm
  - name: configure overlay for munge.key
    shell: "{{ item }}"
    loop:
      - 'wwctl overlay import -p --noupdate generic /etc/munge/munge.key'
      - 'wwctl overlay chown generic /etc/munge/munge.key 987' 
      - 'wwctl overlay import -p --noupdate generic /var/log/munge/munged.log'
      - 'wwctl overlay chown generic /var/log/munge/munged.log 987' 
    #  - 'wwctl overlay chown generic /var/lib/munge 987' 
      - 'wwctl overlay build -O generic node1 node2 node3'
  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:
      - munge
