---
- name: run timesync playbook
  import_playbook: ./timesync.yaml

- name: setup slurm
  hosts: localhost
  tasks:
  - name: create slurm user
    user:
      name: slurm
      uid: 800
      create_home: false
      system: true
  - name: install slurm packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - munge
      - munge-libs
      - slurm
      - slurm-perlapi
  - name: install slurmd
    yum:
      name: slurm-slurmd
      state: present

  - name: enable munge
    shell: 'systemctl enable munge'
