---
- name: run timesync playbook
  import_playbook: ./timesync.yaml

- name: setup slurm
  hosts: localhost
  tasks:
  - name: install slurm packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - munge
      - slurm
      - slurm-slurmctld
  - name: create slurm user
    user:
      name: slurm
      uid: 800
      create_home: false
      system: true
      groups: munge
  - name: syncuser and generate munge key
    shell: "{{ item }}"
    loop:
      - 'wwctl container syncuser --write rockylinux-9 --build'
      - 'create-munge-key'
  - name: chmod /etc/munge
    file:
      path: /etc/munge
      state: directory
      mode: '0755'
  - name: chown munge.key
    file:
      path: /etc/munge/munge.key
      mode: '0600'
      owner: munge
      group: munge
  - name: configure overlay for munge.key
    shell: "{{ item }}"
    loop:
      - 'wwctl overlay create slurm'
      - 'wwctl overlay import -p slurm /etc/munge/munge.key'
      - 'wwctl overlay chmod slurm /etc/munge 0755'
      - "echo 'y' | wwctl profile set default --runtime=generic,slurm"
      - 'wwctl overlay build -NH'
  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:
      - munge

  - name: ports
    firewalld:
      port: "{{ item }}"
      state: enabled
      immediate: true
      permanent: true
    loop:
      - 6817/tcp
      - 4050/udp
  - name: copy slurm config file
    template:
      src: slurm.j2
      dest: /etc/slurm/slurm.conf
  - name: create filesystem
    shell: "echo 'y' | wwctl node set node1 node2 node3 --diskname /dev/sda --diskwipe --partname scratch --partcreate --partnumber 1 --fsname scratch --fsformat ext4 --fspath /scratch"
  - name: slurmctld service runs as slurm user
    lineinfile:
      path: /usr/lib/systemd/system/slurmctld.service
      insertafter: '^\[Service\]$'
      line: "{{ item }}"
      state: present
    loop:
      - 'Group=slurm'
      - 'User=slurm'
  - name: slurm permissions
    shell: "{{ item }}"
    loop:
      - 'mkdir -p /var/log/slurm /var/run/slurm /var/spool/slurm.state'
      - 'chown -R slurm:slurm /var/log/slurm /var/run/slurm /var/spool/slurm.state'
      - 'chmod -R 755 /var/log/slurm /var/run/slurm /var/spool/slurm.state'
  - name: restart
    service: 
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:
      - firewalld
      - slurmctld
