---
- name: run timesync playbook
  import_playbook: ./timesync.yaml

- name: setup slurm
  hosts: localhost
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - munge
      - slurm  
      - ignition
      - gdisk
  - name: create slurm user
    user:
      name: slurm
      uid: 800
      create_home: false
      system: true
      groups: munge
  - name: install slurmd
    yum:
      name: slurm-slurmd
      state: present
  - name: enable munge
    shell: 'systemctl enable munge'
  - name: slurm
    template:
      src: slurm.j2
      dest: /etc/slurm/slurm.conf
  - name: slurmd service runs as slurm user
    lineinfile:
      path: /usr/lib/systemd/system/slurmd.service
      insertafter: '^\[Service\]$'
      line: "{{ item }}"
      state: present
    loop:
      - 'Group=slurm'
      - 'User=slurm'
  - name: enable slurmd
    shell: 'systemctl enable slurmd'
