---
- name: setup john the ripper
  hosts: localhost
  tasks:
  - name: install build dependencies
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - make
      - gcc
      - openssl-devel
  - name: git clone
    git:
      repo: 'https://github.com/openwall/john.git'
      dest: /opt/john
      clone: true
  - name: compile john
    shell: "{{ item }}"
    args:
      chdir: /opt/john/src
    loop:
      - './configure && make -sj4'
      - 'make -s clean && make -sj4'
  - name: create alias for john
    lineinfile:
      path: '/root/.bashrc'
      line: 'alias john=/opt/john/run/john'

