---
- name: setup john the ripper
  hosts: localhost
  tasks:
  - name: install build dependencies
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - make
      - gcc
      - openssl-devel
  - name:
    git:
      repo: 'https://github.com/openwall/john.git'
      dest: /opt/john
      clone: true

